In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sqlalchemy import create_engine

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [4]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Rajdeep123+@localhost:5432/shopsphere_analytics"
)

print("Database connection created.")

Database connection created.

In [5]:
with engine.connect() as connection:
    print("PostgreSQL connection successful!")

PostgreSQL connection successful!

In [6]:
customers = pd.read_sql("""
    SELECT *
    FROM customers;
""", engine)

orders = pd.read_sql("""
    SELECT *
    FROM orders;
""", engine)

print("Customers:", customers.shape)
print("Orders:", orders.shape)

Customers: (10000, 9)
Orders: (55000, 9)

In [7]:
customers.head()

,customer_id,signup_date,age,gender,city,state,region,subscription_type,acquisition_channel
0,C00001,2025-08-14,58.0,Female,Ahmedabad,Gujarat,West,Free,Email
1,C00002,2025-09-07,46.0,Male,Chennai,Tamil Nadu,South,Free,Paid Ads
2,C00003,2025-04-03,60.0,Other,Delhi,Delhi,North,Basic,Organic
3,C00004,2025-04-22,53.0,Male,Jaipur,Rajasthan,North,Free,Organic
4,C00005,2025-05-15,31.0,Male,Guwahati,Assam,East,Free,Paid Ads

In [8]:
orders.head()

,order_id,customer_id,order_date,order_status,payment_method,discount,shipping_fee,total_revenue,total_profit
0,O000001,C09478,2025-11-12 08:08:06,Completed,COD,500.0,45.7,4124.81,1926.26
1,O000002,C09289,2025-11-05 11:24:50,Completed,Wallet,150.0,0.0,1270.64,567.88
2,O000003,C01241,2025-09-23 06:13:21,Completed,Wallet,150.0,0.0,2926.57,1633.88
3,O000004,C00530,2025-08-10 14:27:50,Completed,UPI,50.0,103.9,2557.05,1045.12
4,O000005,C07751,2025-06-09 05:44:45,Completed,Wallet,100.0,0.0,0.00,-100.00

In [9]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

print("Order date range:")
print(orders["order_date"].min(), "to", orders["order_date"].max())

print("\nOrder status:")
print(orders["order_status"].value_counts())

Order date range:
2025-01-01 00:00:46 to 2025-12-30 23:54:47

Order status:
order_status
Completed    51726
Cancelled     3274
Name: count, dtype: int64

In [10]:
completed_orders = orders[
    orders["order_status"] == "Completed"
].copy()

completed_orders["order_date"] = pd.to_datetime(
    completed_orders["order_date"]
)

feature_period = completed_orders[
    completed_orders["order_date"] < "2025-10-01"
]

prediction_period = completed_orders[
    completed_orders["order_date"] >= "2025-10-01"
]

print("Feature-period completed orders:", len(feature_period))
print("Prediction-period completed orders:", len(prediction_period))

print(
    "Customers active before Oct:",
    feature_period["customer_id"].nunique()
)

print(
    "Customers purchasing Oct-Dec:",
    prediction_period["customer_id"].nunique()
)

Feature-period completed orders: 38894
Prediction-period completed orders: 12832
Customers active before Oct: 9648
Customers purchasing Oct-Dec: 7027

In [11]:
# Customers active during the feature period
feature_customers = set(
    feature_period["customer_id"].unique()
)

# Customers who purchased during the prediction period
future_customers = set(
    prediction_period["customer_id"].unique()
)

# Create customer-level target
churn_target = pd.DataFrame({
    "customer_id": list(feature_customers)
})

churn_target["churn"] = (
    ~churn_target["customer_id"].isin(future_customers)
).astype(int)

print(churn_target["churn"].value_counts())

print("\nChurn rate:")
print(
    round(churn_target["churn"].mean() * 100, 2),
    "%"
)

churn
0    6800
1    2848
Name: count, dtype: int64

Churn rate:
29.52 %

In [12]:
# Create customer-level behavioral features
customer_features = (
    feature_period
    .groupby("customer_id")
    .agg(
        total_orders=("order_id", "count"),
        total_revenue=("total_revenue", "sum"),
        total_profit=("total_profit", "sum"),
        avg_order_value=("total_revenue", "mean"),
        avg_discount=("discount", "mean"),
        first_order_date=("order_date", "min"),
        last_order_date=("order_date", "max")
    )
    .reset_index()
)

# Calculate customer recency at the end of the feature period
feature_end_date = pd.Timestamp("2025-09-30 23:59:59")

customer_features["recency_days"] = (
    feature_end_date - customer_features["last_order_date"]
).dt.days

# Add customer profile information
customer_features = customer_features.merge(
    customers[
        [
            "customer_id",
            "age",
            "gender",
            "region",
            "subscription_type",
            "acquisition_channel"
        ]
    ],
    on="customer_id",
    how="left"
)

# Add churn target
customer_features = customer_features.merge(
    churn_target,
    on="customer_id",
    how="left"
)

print("Dataset shape:", customer_features.shape)

customer_features.head()

Dataset shape: (9648, 15)

,customer_id,total_orders,total_revenue,total_profit,avg_order_value,avg_discount,first_order_date,last_order_date,recency_days,age,gender,region,subscription_type,acquisition_channel,churn
0,C00001,3,6360.72,3085.46,2120.240000,100.000000,2025-02-01 06:12:39,2025-06-02 11:58:26,120,58.0,Female,West,Free,Email,1
1,C00002,3,17368.99,8064.18,5789.663333,133.333333,2025-02-03 06:28:11,2025-05-02 23:51:43,151,46.0,Male,South,Free,Paid Ads,0
2,C00003,5,26427.28,15231.34,5285.456000,80.000000,2025-02-26 13:53:31,2025-09-21 06:06:29,9,60.0,Other,North,Basic,Organic,0
3,C00004,5,24860.55,12195.13,4972.110000,140.000000,2025-04-10 15:34:43,2025-09-25 01:18:57,5,53.0,Male,North,Free,Organic,1
4,C00005,3,10568.22,4319.40,3522.740000,216.666667,2025-03-19 03:22:11,2025-06-22 14:40:40,100,31.0,Male,East,Free,Paid Ads,1

In [13]:
# Return and cancellation behavior during the feature period

order_behavior = (
    orders[
        orders["order_date"] < "2025-10-01"
    ]
    .groupby("customer_id")
    .agg(
        total_all_orders=("order_id", "count"),
        cancelled_orders=("order_status", lambda x: (x == "Cancelled").sum())
    )
    .reset_index()
)

# Merge into customer features
customer_features = customer_features.merge(
    order_behavior,
    on="customer_id",
    how="left"
)

# Calculate cancellation rate
customer_features["cancellation_rate"] = (
    customer_features["cancelled_orders"]
    / customer_features["total_all_orders"]
)

# Avoid division problems
customer_features["cancellation_rate"] = (
    customer_features["cancellation_rate"].fillna(0)
)

# Customer activity duration
customer_features["customer_lifetime_days"] = (
    customer_features["last_order_date"]
    - customer_features["first_order_date"]
).dt.days

customer_features["customer_lifetime_days"] = (
    customer_features["customer_lifetime_days"].fillna(0)
)

print(customer_features.shape)
customer_features.head()

(9648, 19)

,customer_id,total_orders,total_revenue,total_profit,avg_order_value,avg_discount,first_order_date,last_order_date,recency_days,age,gender,region,subscription_type,acquisition_channel,churn,total_all_orders,cancelled_orders,cancellation_rate,customer_lifetime_days
0,C00001,3,6360.72,3085.46,2120.240000,100.000000,2025-02-01 06:12:39,2025-06-02 11:58:26,120,58.0,Female,West,Free,Email,1,3,0,0.00,121
1,C00002,3,17368.99,8064.18,5789.663333,133.333333,2025-02-03 06:28:11,2025-05-02 23:51:43,151,46.0,Male,South,Free,Paid Ads,0,3,0,0.00,88
2,C00003,5,26427.28,15231.34,5285.456000,80.000000,2025-02-26 13:53:31,2025-09-21 06:06:29,9,60.0,Other,North,Basic,Organic,0,5,0,0.00,206
3,C00004,5,24860.55,12195.13,4972.110000,140.000000,2025-04-10 15:34:43,2025-09-25 01:18:57,5,53.0,Male,North,Free,Organic,1,5,0,0.00,167
4,C00005,3,10568.22,4319.40,3522.740000,216.666667,2025-03-19 03:22:11,2025-06-22 14:40:40,100,31.0,Male,East,Free,Paid Ads,1,4,1,0.25,95

In [15]:
operations = pd.read_sql("""
    SELECT *
    FROM operations;
""", engine)

print("Operations shape:", operations.shape)
print(operations.columns.tolist())

Operations shape: (55000, 8)
['order_id', 'delivery_date', 'promised_date', 'delivery_days', 'delivery_status', 'cancellation_flag', 'return_flag', 'return_reason']

In [16]:
operations["order_id"] = operations["order_id"].astype(str)
orders["order_id"] = orders["order_id"].astype(str)

operations["return_flag"] = operations["return_flag"].fillna(0).astype(int)

In [17]:
return_behavior = (
    operations[
        operations["order_id"].isin(
            feature_period["order_id"]
        )
    ]
    .groupby("order_id")
    .agg(
        returned=("return_flag", "max")
    )
    .reset_index()
)

return_behavior = (
    return_behavior
    .merge(
        orders[["order_id", "customer_id"]],
        on="order_id",
        how="left"
    )
    .groupby("customer_id")
    .agg(
        returned_orders=("returned", "sum"),
        total_operation_orders=("order_id", "count")
    )
    .reset_index()
)

customer_features = customer_features.merge(
    return_behavior,
    on="customer_id",
    how="left"
)

customer_features["returned_orders"] = (
    customer_features["returned_orders"].fillna(0)
)

customer_features["total_operation_orders"] = (
    customer_features["total_operation_orders"].fillna(0)
)

customer_features["return_rate"] = np.where(
    customer_features["total_operation_orders"] > 0,
    customer_features["returned_orders"]
    / customer_features["total_operation_orders"],
    0
)

print(customer_features.shape)
customer_features.head()

(9648, 22)

,customer_id,total_orders,total_revenue,total_profit,avg_order_value,avg_discount,first_order_date,last_order_date,recency_days,age,...,subscription_type,acquisition_channel,churn,total_all_orders,cancelled_orders,cancellation_rate,customer_lifetime_days,returned_orders,total_operation_orders,return_rate
0,C00001,3,6360.72,3085.46,2120.240000,100.000000,2025-02-01 06:12:39,2025-06-02 11:58:26,120,58.0,...,Free,Email,1,3,0,0.00,121,0,3,0.000000
1,C00002,3,17368.99,8064.18,5789.663333,133.333333,2025-02-03 06:28:11,2025-05-02 23:51:43,151,46.0,...,Free,Paid Ads,0,3,0,0.00,88,0,3,0.000000
2,C00003,5,26427.28,15231.34,5285.456000,80.000000,2025-02-26 13:53:31,2025-09-21 06:06:29,9,60.0,...,Basic,Organic,0,5,0,0.00,206,0,5,0.000000
3,C00004,5,24860.55,12195.13,4972.110000,140.000000,2025-04-10 15:34:43,2025-09-25 01:18:57,5,53.0,...,Free,Organic,1,5,0,0.00,167,1,5,0.200000
4,C00005,3,10568.22,4319.40,3522.740000,216.666667,2025-03-19 03:22:11,2025-06-22 14:40:40,100,31.0,...,Free,Paid Ads,1,4,1,0.25,95,2,3,0.666667

In [18]:
missing_values = (
    customer_features.isnull()
    .sum()
    .sort_values(ascending=False)
)

print(missing_values[missing_values > 0])

age    239
dtype: int64

In [19]:
print("Rows:", customer_features.shape[0])
print("Columns:", customer_features.shape[1])

print("\nChurn distribution:")
print(customer_features["churn"].value_counts())

print("\nChurn percentage:")
print(
    customer_features["churn"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Rows: 9648
Columns: 22

Churn distribution:
churn
0    6800
1    2848
Name: count, dtype: int64

Churn percentage:
churn
0    70.48
1    29.52
Name: proportion, dtype: float64

In [20]:
missing_values = customer_features.isnull().sum()

print(
    missing_values[missing_values > 0]
)

age    239
dtype: int64

In [21]:
# Fill missing ages with the median age

median_age = customer_features["age"].median()

customer_features["age"] = (
    customer_features["age"].fillna(median_age)
)

print("Median age used:", median_age)

print(
    "Missing ages after filling:",
    customer_features["age"].isnull().sum()
)

Median age used: 39.0
Missing ages after filling: 0

In [22]:
print(customer_features.info())

<class 'pandas.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             9648 non-null   str
 1   total_orders            9648 non-null   int64
 2   total_revenue           9648 non-null   float64
 3   total_profit            9648 non-null   float64
 4   avg_order_value         9648 non-null   float64
 5   avg_discount            9648 non-null   float64
 6   first_order_date        9648 non-null   datetime64[us]
 7   last_order_date         9648 non-null   datetime64[us]
 8   recency_days            9648 non-null   int64
 9   age                     9648 non-null   float64
 10  gender                  9648 non-null   str
 11  region                  9648 non-null   str
 12  subscription_type       9648 non-null   str
 13  acquisition_channel     9648 non-null   str
 14  churn                   9648 non-null   int64
 15  total_all_orders        9648 non-null   int64
 16  cancelled_orders        9648 non-null   int64
 17  cancellation_rate       9648 non-null   float64
 18  customer_lifetime_days  9648 non-null   int64
 19  returned_orders         9648 non-null   int64
 20  total_operation_orders  9648 non-null   int64
 21  return_rate             9648 non-null   float64
dtypes: datetime64[us](2), float64(7), int64(8), str(5)
memory usage: 1.6 MB
None

In [23]:
print(customer_features.head())

  customer_id  total_orders  total_revenue  total_profit  avg_order_value  \
0      C00001             3        6360.72       3085.46      2120.240000
1      C00002             3       17368.99       8064.18      5789.663333
2      C00003             5       26427.28      15231.34      5285.456000
3      C00004             5       24860.55      12195.13      4972.110000
4      C00005             3       10568.22       4319.40      3522.740000

   avg_discount    first_order_date     last_order_date  recency_days   age  \
0    100.000000 2025-02-01 06:12:39 2025-06-02 11:58:26           120  58.0
1    133.333333 2025-02-03 06:28:11 2025-05-02 23:51:43           151  46.0
2     80.000000 2025-02-26 13:53:31 2025-09-21 06:06:29             9  60.0
3    140.000000 2025-04-10 15:34:43 2025-09-25 01:18:57             5  53.0
4    216.666667 2025-03-19 03:22:11 2025-06-22 14:40:40           100  31.0

   ... subscription_type acquisition_channel churn total_all_orders  \
0  ...              Free               Email     1                3
1  ...              Free            Paid Ads     0                3
2  ...             Basic             Organic     0                5
3  ...              Free             Organic     1                5
4  ...              Free            Paid Ads     1                4

   cancelled_orders  cancellation_rate  customer_lifetime_days  \
0                 0               0.00                     121
1                 0               0.00                      88
2                 0               0.00                     206
3                 0               0.00                     167
4                 1               0.25                      95

   returned_orders  total_operation_orders  return_rate
0                0                       3     0.000000
1                0                       3     0.000000
2                0                       5     0.000000
3                1                       5     0.200000
4                2                       3     0.666667

[5 rows x 22 columns]

In [24]:
print("Gender:", customer_features["gender"].unique())
print("Region:", customer_features["region"].unique())
print("Subscription:", customer_features["subscription_type"].unique())
print("Acquisition:", customer_features["acquisition_channel"].unique())

Gender: <StringArray>
['Female', 'Male', 'Other']
Length: 3, dtype: str
Region: <StringArray>
['West', 'South', 'North', 'East']
Length: 4, dtype: str
Subscription: <StringArray>
['Free', 'Basic', 'Premium']
Length: 3, dtype: str
Acquisition: <StringArray>
['Email', 'Paid Ads', 'Organic', 'Referral', 'Social Media']
Length: 5, dtype: str

In [25]:
feature_columns = [
    "total_orders",
    "total_revenue",
    "total_profit",
    "avg_order_value",
    "avg_discount",
    "recency_days",
    "age",
    "gender",
    "region",
    "subscription_type",
    "acquisition_channel",
    "total_all_orders",
    "cancelled_orders",
    "cancellation_rate",
    "customer_lifetime_days",
    "returned_orders",
    "total_operation_orders",
    "return_rate"
]

X = customer_features[feature_columns].copy()
y = customer_features["churn"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print(y.value_counts(normalize=True).mul(100).round(2))

X shape: (9648, 18)
y shape: (9648,)

Target distribution:
churn
0    6800
1    2848
Name: count, dtype: int64

Target percentage:
churn
0    70.48
1    29.52
Name: proportion, dtype: float64

In [26]:
categorical_features = [
    "gender",
    "region",
    "subscription_type",
    "acquisition_channel"
]

numerical_features = [
    "total_orders",
    "total_revenue",
    "total_profit",
    "avg_order_value",
    "avg_discount",
    "recency_days",
    "age",
    "total_all_orders",
    "cancelled_orders",
    "cancellation_rate",
    "customer_lifetime_days",
    "returned_orders",
    "total_operation_orders",
    "return_rate"
]

print("Categorical features:", categorical_features)
print("Number of categorical features:", len(categorical_features))

print("\nNumerical features:", numerical_features)
print("Number of numerical features:", len(numerical_features))

Categorical features: ['gender', 'region', 'subscription_type', 'acquisition_channel']
Number of categorical features: 4

Numerical features: ['total_orders', 'total_revenue', 'total_profit', 'avg_order_value', 'avg_discount', 'recency_days', 'age', 'total_all_orders', 'cancelled_orders', 'cancellation_rate', 'customer_lifetime_days', 'returned_orders', 'total_operation_orders', 'return_rate']
Number of numerical features: 14

In [28]:
import sklearn

print("scikit-learn version:", sklearn.__version__)

scikit-learn version: 1.9.0

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                drop="first"
            ),
            categorical_features
        )
    ]
)

print("Preprocessor created successfully.")

Preprocessor created successfully.

In [30]:
# Time-based train/test split
train_mask = customer_features["last_order_date"] < "2025-10-01"

X_train = X.loc[train_mask].copy()
y_train = y.loc[train_mask].copy()

X_test = X.loc[~train_mask].copy()
y_test = y.loc[~train_mask].copy()

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTest target distribution:")
print(y_test.value_counts())

Training set: (9648, 18)
Test set: (0, 18)

Training target distribution:
churn
0    6800
1    2848
Name: count, dtype: int64

Test target distribution:
Series([], Name: count, dtype: int64)

In [31]:
print("X type:", type(X))
print("y type:", type(y))

print("X shape:", X.shape)
print("y shape:", y.shape)

print("X index:", X.index.min(), "to", X.index.max())
print("y index:", y.index.min(), "to", y.index.max())

print("\ntrain_test_split function:")
print(train_test_split)

X type: <class 'pandas.DataFrame'>
y type: <class 'pandas.Series'>
X shape: (9648, 18)
y shape: (9648,)
X index: 0 to 9647
y index: 0 to 9647

train_test_split function:

NameError: name 'train_test_split' is not defined

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTest target distribution:")
print(y_test.value_counts())

Training set: (7718, 18)
Test set: (1930, 18)

Training target distribution:
churn
0    5440
1    2278
Name: count, dtype: int64

Test target distribution:
churn
0    1360
1     570
Name: count, dtype: int64

In [33]:
# Fit preprocessing only on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform test data using the already-fitted preprocessor
X_test_processed = preprocessor.transform(X_test)

print("Processed training shape:", X_train_processed.shape)
print("Processed test shape:", X_test_processed.shape)

Processed training shape: (7718, 25)
Processed test shape: (1930, 25)

In [34]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_processed, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [35]:
# Generate predictions
y_pred = logistic_model.predict(X_test_processed)

print("Predictions generated successfully.")

print("\nFirst 20 predictions:")
print(y_pred[:20])

Predictions generated successfully.

First 20 predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [36]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# ROC-AUC requires probability scores, not class predictions
y_pred_proba = logistic_model.predict_proba(X_test_processed)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)

print("Logistic Regression Performance")
print("--------------------------------")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {roc_auc:.4f}")

Logistic Regression Performance
--------------------------------
Accuracy : 0.7047
Precision: 0.0000
Recall   : 0.0000
F1 Score : 0.0000
ROC-AUC  : 0.6081

c:\Users\sahar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [37]:
print("Predicted classes:")
print(pd.Series(y_pred).value_counts())

print("\nActual classes:")
print(y_test.value_counts())

Predicted classes:
0    1930
Name: count, dtype: int64

Actual classes:
churn
0    1360
1     570
Name: count, dtype: int64

In [38]:
# Examine predicted churn probabilities
print("Probability summary:")
print(pd.Series(y_pred_proba).describe())

print("\nProbability percentiles:")
print(
    pd.Series(y_pred_proba).quantile(
        [0, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.00]
    )
)

Probability summary:
count    1930.000000
mean        0.298954
std         0.105167
min         0.075345
25%         0.242297
50%         0.325059
75%         0.391497
max         0.477505
dtype: float64

Probability percentiles:
0.00    0.075345
0.25    0.242297
0.50    0.325059
0.75    0.391497
0.90    0.408705
0.95    0.418901
0.99    0.436031
1.00    0.477505
dtype: float64

In [39]:
probability_analysis = pd.DataFrame({
    "actual_churn": y_test.values,
    "predicted_probability": y_pred_proba
})

print("Average predicted probability:")
print(
    probability_analysis.groupby("actual_churn")["predicted_probability"]
    .mean()
)

print("\nMedian predicted probability:")
print(
    probability_analysis.groupby("actual_churn")["predicted_probability"]
    .median()
)

Average predicted probability:
actual_churn
0    0.285775
1    0.330399
Name: predicted_probability, dtype: float64

Median predicted probability:
actual_churn
0    0.277103
1    0.372858
Name: predicted_probability, dtype: float64

In [40]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_pred_proba
)

f1_scores = (
    2 * precision[:-1] * recall[:-1]
    / (precision[:-1] + recall[:-1] + 1e-10)
)

best_idx = f1_scores.argmax()
best_threshold = thresholds[best_idx]
best_f1 = f1_scores[best_idx]

print("Best threshold:", round(best_threshold, 4))
print("Best F1 Score:", round(best_f1, 4))
print("Precision at best threshold:", round(precision[best_idx], 4))
print("Recall at best threshold:", round(recall[best_idx], 4))

Best threshold: 0.2212
Best F1 Score: 0.491
Precision at best threshold: 0.3361
Recall at best threshold: 0.9105

In [41]:
# Apply optimized threshold
y_pred_threshold = (y_pred_proba >= best_threshold).astype(int)

print("Predicted class distribution:")
print(pd.Series(y_pred_threshold).value_counts())

print("\nActual class distribution:")
print(y_test.value_counts())

Predicted class distribution:
1    1544
0     386
Name: count, dtype: int64

Actual class distribution:
churn
0    1360
1     570
Name: count, dtype: int64

In [42]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_pred_threshold)

print("Confusion Matrix:")
print(cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_threshold,
        target_names=["Retained", "Churned"]
    )
)

Confusion Matrix:
[[ 335 1025]
 [  51  519]]

Classification Report:
              precision    recall  f1-score   support

    Retained       0.87      0.25      0.38      1360
     Churned       0.34      0.91      0.49       570

    accuracy                           0.44      1930
   macro avg       0.60      0.58      0.44      1930
weighted avg       0.71      0.44      0.42      1930

In [43]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

random_forest.fit(X_train_processed, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.

In [44]:
# Random Forest predictions
rf_pred = random_forest.predict(X_test_processed)

# Churn probabilities
rf_pred_proba = random_forest.predict_proba(X_test_processed)[:, 1]

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_roc_auc = roc_auc_score(y_test, rf_pred_proba)

print("Random Forest Performance")
print("--------------------------------")
print(f"Accuracy : {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall   : {rf_recall:.4f}")
print(f"F1 Score : {rf_f1:.4f}")
print(f"ROC-AUC  : {rf_roc_auc:.4f}")

Random Forest Performance
--------------------------------
Accuracy : 0.6181
Precision: 0.3664
Recall   : 0.4018
F1 Score : 0.3833
ROC-AUC  : 0.6102

In [45]:
from sklearn.metrics import precision_recall_curve

rf_precision_curve, rf_recall_curve, rf_thresholds = precision_recall_curve(
    y_test,
    rf_pred_proba
)

rf_f1_scores = (
    2 * rf_precision_curve[:-1] * rf_recall_curve[:-1]
    / (
        rf_precision_curve[:-1]
        + rf_recall_curve[:-1]
        + 1e-10
    )
)

rf_best_idx = rf_f1_scores.argmax()

rf_best_threshold = rf_thresholds[rf_best_idx]
rf_best_f1 = rf_f1_scores[rf_best_idx]

print("Best RF threshold:", round(rf_best_threshold, 4))
print("Best RF F1 Score:", round(rf_best_f1, 4))
print(
    "Precision at best threshold:",
    round(rf_precision_curve[rf_best_idx], 4)
)
print(
    "Recall at best threshold:",
    round(rf_recall_curve[rf_best_idx], 4)
)

Best RF threshold: 0.3508
Best RF F1 Score: 0.4916
Precision at best threshold: 0.3499
Recall at best threshold: 0.8263

In [46]:
feature_names = preprocessor.get_feature_names_out()

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": random_forest.feature_importances_
})

feature_importance = (
    feature_importance
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
)

print("Top 15 churn features:")
print(feature_importance.head(15))

Top 15 churn features:
                             feature  importance
0                  num__total_profit    0.106781
1               num__avg_order_value    0.104424
2                 num__total_revenue    0.103733
3                  num__recency_days    0.102718
4        num__customer_lifetime_days    0.095924
5                           num__age    0.090169
6                  num__avg_discount    0.086249
7        cat__subscription_type_Free    0.039309
8     cat__subscription_type_Premium    0.034729
9              num__total_all_orders    0.027409
10                 num__total_orders    0.021397
11       num__total_operation_orders    0.021217
12                  num__return_rate    0.020614
13                  cat__gender_Male    0.017004
14  cat__acquisition_channel_Organic    0.014569

In [47]:
print("Feature dataset shape:", customer_features.shape)

print("\nFeature columns:")
for col in customer_features.columns:
    print("-", col)

print("\nDate range used in feature dataset:")
print("First order:", customer_features["first_order_date"].min())
print("Last order:", customer_features["last_order_date"].max())

Feature dataset shape: (9648, 22)

Feature columns:
- customer_id
- total_orders
- total_revenue
- total_profit
- avg_order_value
- avg_discount
- first_order_date
- last_order_date
- recency_days
- age
- gender
- region
- subscription_type
- acquisition_channel
- churn
- total_all_orders
- cancelled_orders
- cancellation_rate
- customer_lifetime_days
- returned_orders
- total_operation_orders
- return_rate

Date range used in feature dataset:
First order: 2025-01-01 00:00:46
Last order: 2025-09-30 23:58:08

In [48]:
rf_pred_threshold = (
    rf_pred_proba >= rf_best_threshold
).astype(int)

print("Predicted class distribution:")
print(pd.Series(rf_pred_threshold).value_counts())

print("\nActual class distribution:")
print(y_test.value_counts())

Predicted class distribution:
1    1346
0     584
Name: count, dtype: int64

Actual class distribution:
churn
0    1360
1     570
Name: count, dtype: int64

In [49]:
from sklearn.metrics import confusion_matrix, classification_report

rf_cm = confusion_matrix(
    y_test,
    rf_pred_threshold
)

print("Random Forest Confusion Matrix:")
print(rf_cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        rf_pred_threshold,
        target_names=["Retained", "Churned"]
    )
)

Random Forest Confusion Matrix:
[[485 875]
 [ 99 471]]

Classification Report:
              precision    recall  f1-score   support

    Retained       0.83      0.36      0.50      1360
     Churned       0.35      0.83      0.49       570

    accuracy                           0.50      1930
   macro avg       0.59      0.59      0.50      1930
weighted avg       0.69      0.50      0.50      1930

In [50]:
# Create customer-level churn predictions
churn_predictions = X_test.copy()

churn_predictions["actual_churn"] = y_test.values
churn_predictions["churn_probability"] = y_pred_proba
churn_predictions["predicted_churn"] = y_pred_threshold

print("Prediction dataset shape:", churn_predictions.shape)

print("\nSample predictions:")
print(
    churn_predictions[
        ["churn_probability", "predicted_churn", "actual_churn"]
    ].head(10)
)

Prediction dataset shape: (1930, 21)

Sample predictions:
      churn_probability  predicted_churn  actual_churn
3044           0.388349                1             0
1228           0.247960                1             0
8138           0.376766                1             1
9215           0.378287                1             1
4603           0.427651                1             1
5335           0.316972                1             0
2470           0.123312                0             1
6117           0.401635                1             0
1472           0.260738                1             1
3090           0.113738                0             0

In [51]:
churn_predictions["risk_segment"] = pd.cut(
    churn_predictions["churn_probability"],
    bins=[0, 0.20, 0.35, 1.00],
    labels=["Low Risk", "Medium Risk", "High Risk"],
    include_lowest=True
)

print("Risk segment distribution:")
print(
    churn_predictions["risk_segment"]
    .value_counts()
    .sort_index()
)

print("\nRisk segment percentages:")
print(
    churn_predictions["risk_segment"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Risk segment distribution:
risk_segment
Low Risk       351
Medium Risk    658
High Risk      921
Name: count, dtype: int64

Risk segment percentages:
risk_segment
Low Risk       18.19
Medium Risk    34.09
High Risk      47.72
Name: proportion, dtype: float64

In [52]:
risk_validation = (
    churn_predictions
    .groupby("risk_segment", observed=True)
    .agg(
        customers=("actual_churn", "count"),
        actual_churners=("actual_churn", "sum"),
        actual_churn_rate=("actual_churn", "mean")
    )
)

risk_validation["actual_churn_rate"] = (
    risk_validation["actual_churn_rate"] * 100
).round(2)

print(risk_validation)

              customers  actual_churners  actual_churn_rate
risk_segment
Low Risk            351               45              12.82
Medium Risk         658              177              26.90
High Risk           921              348              37.79

In [53]:
overall_churn_rate = y_test.mean() * 100

high_risk_churn_rate = (
    risk_validation.loc["High Risk", "actual_churn_rate"]
)

low_risk_churn_rate = (
    risk_validation.loc["Low Risk", "actual_churn_rate"]
)

high_risk_lift = high_risk_churn_rate / overall_churn_rate
low_vs_high_ratio = high_risk_churn_rate / low_risk_churn_rate

print(f"Overall test churn rate: {overall_churn_rate:.2f}%")
print(f"High-risk churn rate: {high_risk_churn_rate:.2f}%")
print(f"High-risk lift: {high_risk_lift:.2f}x")
print(f"High vs Low risk ratio: {low_vs_high_ratio:.2f}x")

Overall test churn rate: 29.53%
High-risk churn rate: 37.79%
High-risk lift: 1.28x
High vs Low risk ratio: 2.95x

In [54]:
# Add customer IDs back to the prediction dataset
churn_predictions["customer_id"] = customer_features.loc[
    X_test.index,
    "customer_id"
].values

# Reorder the important columns
prediction_output = churn_predictions[
    [
        "customer_id",
        "churn_probability",
        "risk_segment",
        "predicted_churn",
        "actual_churn"
    ]
].copy()

prediction_output = prediction_output.sort_values(
    "churn_probability",
    ascending=False
).reset_index(drop=True)

print("Prediction output shape:", prediction_output.shape)

print("\nTop 20 highest-risk customers:")
print(prediction_output.head(20))

Prediction output shape: (1930, 5)

Top 20 highest-risk customers:
   customer_id  churn_probability risk_segment  predicted_churn  actual_churn
0       C09624           0.477505    High Risk                1             0
1       C00385           0.470133    High Risk                1             0
2       C09312           0.469515    High Risk                1             0
3       C04911           0.459498    High Risk                1             0
4       C02993           0.456405    High Risk                1             1
5       C00559           0.454527    High Risk                1             1
6       C09614           0.447058    High Risk                1             1
7       C01396           0.446975    High Risk                1             0
8       C02467           0.445835    High Risk                1             0
9       C03220           0.445465    High Risk                1             0
10      C07160           0.442933    High Risk                1             0
11      C03066           0.442194    High Risk                1             0
12      C09370           0.441709    High Risk                1             1
13      C07633           0.441590    High Risk                1             1
14      C04866           0.439868    High Risk                1             0
15      C00740           0.438412    High Risk                1             0
16      C02531           0.438139    High Risk                1             0
17      C01518           0.437888    High Risk                1             1
18      C03881           0.437457    High Risk                1             0
19      C00670           0.436106    High Risk                1             1

In [55]:
customer_context = customer_features[
    [
        "customer_id",
        "total_orders",
        "total_revenue",
        "total_profit",
        "avg_order_value",
        "avg_discount",
        "recency_days",
        "age",
        "region",
        "subscription_type",
        "acquisition_channel",
        "cancelled_orders",
        "cancellation_rate",
        "customer_lifetime_days",
        "returned_orders",
        "return_rate"
    ]
].copy()

prediction_output = prediction_output.merge(
    customer_context,
    on="customer_id",
    how="left"
)

print("Final churn output shape:", prediction_output.shape)

print("\nTop 10 high-risk customers:")
print(
    prediction_output[
        [
            "customer_id",
            "churn_probability",
            "risk_segment",
            "total_revenue",
            "total_profit",
            "total_orders",
            "recency_days",
            "subscription_type",
            "region"
        ]
    ].head(10)
)

Final churn output shape: (1930, 20)

Top 10 high-risk customers:
  customer_id  churn_probability risk_segment  total_revenue  total_profit  \
0      C09624           0.477505    High Risk        5388.87       2279.80
1      C00385           0.470133    High Risk        3594.44       1643.82
2      C09312           0.469515    High Risk        2781.14       1177.14
3      C04911           0.459498    High Risk        4014.92       2031.63
4      C02993           0.456405    High Risk         833.57        221.52
5      C00559           0.454527    High Risk         385.45         78.20
6      C09614           0.447058    High Risk       10865.69       5439.69
7      C01396           0.446975    High Risk         939.82        457.60
8      C02467           0.445835    High Risk        6646.15       3306.74
9      C03220           0.445465    High Risk         245.95         48.81

   total_orders  recency_days subscription_type region
0             1           268              Free  North
1             1            83              Free  North
2             1           198              Free   West
3             2            65              Free  South
4             1           262              Free  North
5             1           212              Free  North
6             2           109              Free   East
7             1           111              Free  South
8             2            28              Free   West
9             1           176              Free  North

In [56]:
from sklearn.preprocessing import MinMaxScaler

value_scaler = MinMaxScaler()

prediction_output["customer_value_score"] = (
    value_scaler.fit_transform(
        prediction_output[["total_profit"]]
    ).flatten()
)

print(
    prediction_output[
        [
            "customer_id",
            "churn_probability",
            "total_profit",
            "customer_value_score"
        ]
    ].head(10)
)

  customer_id  churn_probability  total_profit  customer_value_score
0      C09624           0.477505       2279.80              0.075396
1      C00385           0.470133       1643.82              0.058792
2      C09312           0.469515       1177.14              0.046608
3      C04911           0.459498       2031.63              0.068917
4      C02993           0.456405        221.52              0.021659
5      C00559           0.454527         78.20              0.017917
6      C09614           0.447058       5439.69              0.157893
7      C01396           0.446975        457.60              0.027822
8      C02467           0.445835       3306.74              0.102207
9      C03220           0.445465         48.81              0.017150

In [57]:
prediction_output["value_segment"] = pd.qcut(
    prediction_output["total_profit"],
    q=[0, 0.25, 0.75, 1],
    labels=["Low Value", "Medium Value", "High Value"],
    duplicates="drop"
)

print("Value segment distribution:")
print(
    prediction_output["value_segment"]
    .value_counts()
    .sort_index()
)

Value segment distribution:
value_segment
Low Value       483
Medium Value    964
High Value      483
Name: count, dtype: int64

In [58]:
def get_retention_priority(row):
    if row["risk_segment"] == "High Risk" and row["value_segment"] == "High Value":
        return "Critical Priority"
    
    elif row["risk_segment"] == "High Risk" and row["value_segment"] == "Medium Value":
        return "High Priority"
    
    elif row["risk_segment"] == "Medium Risk" and row["value_segment"] == "High Value":
        return "High Priority"
    
    elif row["risk_segment"] == "High Risk" and row["value_segment"] == "Low Value":
        return "Medium Priority"
    
    elif row["risk_segment"] == "Medium Risk" and row["value_segment"] == "Medium Value":
        return "Medium Priority"
    
    elif row["risk_segment"] == "Low Risk" and row["value_segment"] == "High Value":
        return "Maintain"
    
    else:
        return "Monitor"


prediction_output["retention_priority"] = (
    prediction_output.apply(
        get_retention_priority,
        axis=1
    )
)

print("Retention priority distribution:")
print(
    prediction_output["retention_priority"]
    .value_counts()
)

Retention priority distribution:
retention_priority
Medium Priority      670
High Priority        669
Monitor              289
Maintain             197
Critical Priority    105
Name: count, dtype: int64

In [59]:
priority_validation = (
    prediction_output
    .groupby("retention_priority", observed=True)
    .agg(
        customers=("customer_id", "count"),
        avg_churn_probability=("churn_probability", "mean"),
        avg_profit=("total_profit", "mean"),
        actual_churners=("actual_churn", "sum"),
        actual_churn_rate=("actual_churn", "mean")
    )
)

priority_validation["avg_churn_probability"] = (
    priority_validation["avg_churn_probability"] * 100
).round(2)

priority_validation["actual_churn_rate"] = (
    priority_validation["actual_churn_rate"] * 100
).round(2)

priority_validation = priority_validation.sort_values(
    "avg_churn_probability",
    ascending=False
)

print(priority_validation)

                    customers  avg_churn_probability    avg_profit  \
retention_priority
Critical Priority         105                  37.84  13097.253238
High Priority             669                  35.27   7997.802436
Medium Priority           670                  33.23   3611.240985
Monitor                   289                  19.28   3784.509619
Maintain                  197                  11.62  16357.357513

                    actual_churners  actual_churn_rate
retention_priority
Critical Priority                44              41.90
High Priority                   236              35.28
Medium Priority                 203              30.30
Monitor                          62              21.45
Maintain                         25              12.69

In [60]:
priority_financial_summary = (
    prediction_output
    .groupby("retention_priority", observed=True)
    .agg(
        customers=("customer_id", "count"),
        total_historical_profit=("total_profit", "sum"),
        avg_profit=("total_profit", "mean"),
        actual_churners=("actual_churn", "sum")
    )
    .sort_values(
        "total_historical_profit",
        ascending=False
    )
)

print(priority_financial_summary)

                    customers  total_historical_profit    avg_profit  \
retention_priority
High Priority             669               5350529.83   7997.802436
Maintain                  197               3222399.43  16357.357513
Medium Priority           670               2419531.46   3611.240985
Critical Priority         105               1375211.59  13097.253238
Monitor                   289               1093723.28   3784.509619

                    actual_churners
retention_priority
High Priority                   236
Maintain                         25
Medium Priority                 203
Critical Priority                44
Monitor                          62

In [61]:
critical_churners = prediction_output.loc[
    prediction_output["retention_priority"] == "Critical Priority",
    "actual_churn"
].sum()

critical_high_churners = prediction_output.loc[
    prediction_output["retention_priority"].isin(
        ["Critical Priority", "High Priority"]
    ),
    "actual_churn"
].sum()

total_churners = prediction_output["actual_churn"].sum()

critical_profit = prediction_output.loc[
    prediction_output["retention_priority"] == "Critical Priority",
    "total_profit"
].sum()

critical_high_profit = prediction_output.loc[
    prediction_output["retention_priority"].isin(
        ["Critical Priority", "High Priority"]
    ),
    "total_profit"
].sum()

total_profit = prediction_output["total_profit"].sum()

print(f"Total observed churners: {total_churners}")
print(
    f"Critical churn capture: "
    f"{critical_churners / total_churners * 100:.2f}%"
)
print(
    f"Critical + High churn capture: "
    f"{critical_high_churners / total_churners * 100:.2f}%"
)

print(f"\nCritical historical profit: ₹{critical_profit:,.2f}")
print(
    f"Critical + High historical profit: "
    f"₹{critical_high_profit:,.2f}"
)

print(
    f"\nCritical profit share: "
    f"{critical_profit / total_profit * 100:.2f}%"
)

print(
    f"Critical + High profit share: "
    f"{critical_high_profit / total_profit * 100:.2f}%"
)

Total observed churners: 570
Critical churn capture: 7.72%
Critical + High churn capture: 49.12%

Critical historical profit: ₹1,375,211.59
Critical + High historical profit: ₹6,725,741.42

Critical profit share: 10.22%
Critical + High profit share: 49.96%

In [62]:
priority_matrix = pd.crosstab(
    prediction_output["risk_segment"],
    prediction_output["value_segment"]
)

print("Risk × Value Matrix:")
print(priority_matrix)

Risk × Value Matrix:
value_segment  Low Value  Medium Value  High Value
risk_segment
Low Risk              20           134         197
Medium Risk          135           342         181
High Risk            328           488         105

In [63]:
model_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "ROC_AUC": [
        roc_auc,
        rf_roc_auc
    ],
    "Best_F1": [
        best_f1,
        rf_best_f1
    ],
    "Best_Precision": [
        precision[best_idx],
        rf_precision_curve[rf_best_idx]
    ],
    "Best_Recall": [
        recall[best_idx],
        rf_recall_curve[rf_best_idx]
    ]
})

print(model_comparison.round(4))

                 Model  ROC_AUC  Best_F1  Best_Precision  Best_Recall
0  Logistic Regression   0.6081   0.4910          0.3361       0.9105
1        Random Forest   0.6102   0.4916          0.3499       0.8263

In [64]:
# Final dashboard dataset
dashboard_data = prediction_output.copy()

# Add a few useful business metrics
dashboard_data["revenue_per_order"] = (
    dashboard_data["total_revenue"] /
    dashboard_data["total_orders"].replace(0, 1)
)

dashboard_data["profit_margin"] = (
    dashboard_data["total_profit"] /
    dashboard_data["total_revenue"].replace(0, 1)
)

dashboard_data["risk_score"] = (
    dashboard_data["churn_probability"] * 100
).round(2)

# Reorder columns
dashboard_data = dashboard_data[
    [
        "customer_id",
        "churn_probability",
        "risk_score",
        "risk_segment",
        "value_segment",
        "retention_priority",
        "actual_churn",
        "predicted_churn",
        "total_orders",
        "total_revenue",
        "total_profit",
        "profit_margin",
        "avg_order_value",
        "avg_discount",
        "recency_days",
        "age",
        "region",
        "subscription_type",
        "acquisition_channel",
        "cancelled_orders",
        "cancellation_rate",
        "customer_lifetime_days",
        "returned_orders",
        "return_rate",
        "revenue_per_order"
    ]
]

print("Dashboard dataset shape:", dashboard_data.shape)
print("\nColumns:")
print(dashboard_data.columns.tolist())

Dashboard dataset shape: (1930, 25)

Columns:
['customer_id', 'churn_probability', 'risk_score', 'risk_segment', 'value_segment', 'retention_priority', 'actual_churn', 'predicted_churn', 'total_orders', 'total_revenue', 'total_profit', 'profit_margin', 'avg_order_value', 'avg_discount', 'recency_days', 'age', 'region', 'subscription_type', 'acquisition_channel', 'cancelled_orders', 'cancellation_rate', 'customer_lifetime_days', 'returned_orders', 'return_rate', 'revenue_per_order']

In [ ]:
dashboard_data.to_csv(
    "customer_churn_dashboard.csv",
    index=False
)

print("Dashboard CSV created successfully.")

Dashboard CSV created successfully.

:

In [1]:
print("Kernel working")

Kernel working